### ISSUE TITLE
ndarray_listener missing in requirements in meta.yaml

### ISSUE THREAD

**Issue by mwojcikowski** [conda-forge/limix-feedstock#8]
The `ndarray_listener` package is missing in the specs for running the package.

Steps to reproduce:
1. Create clean env: `conda create --name limix_test python=2.7`
2. Activate env: `source activate limix_test`
3. Install limix: `conda install -c conda-forge limix`

Now you cannot import limix: `python -c "import limix"`

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/limix/__init__.py", line 16, in <module>
    from . import (heritability, io, iset, mtset, plot, qtl, scripts, stats, util,
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/limix/heritability/__init__.py", line 15, in <module>
    from .estimate import estimate
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/limix/heritability/estimate.py", line 6, in <module>
    from glimix_core.glmm import GLMM
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/glimix_core/__init__.py", line 12, in <module>
    from . import cov, ggp, glmm, gp, lik, link, lmm, mean, random, util
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/glimix_core/cov/__init__.py", line 43, in <module>
    from .eye import EyeCov
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/glimix_core/cov/eye.py", line 5, in <module>
    from optimix import Function, Scalar
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/optimix/__init__.py", line 9, in <module>
    from . import testing
  File "/home/maciek/miniconda3/envs/limix_test/lib/python2.7/site-packages/optimix/testing.py", line 1, in <module>
    from ndarray_listener import ndarray_listener
ImportError: No module named ndarray_listener
```
Installing `ndarray_listener` fixes the problem: `conda install -c conda-forge ndarray_listener`

**Comment by horta** [comment]
Thanks a lot for the feedback, @mwojcikowski ! I've now resolved the issue. The problem was with the optimix dependency, which I broke the interface by accident when released a new version of it.

Tested limix here and it is now working again!
